name: Say hello
run-name: ${{ github.actor }} pba

on: [push]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: echo "Hola github de ${{ github.actor }}!!!"

  hello_world_2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: echo "${{ github.actor }} - ${{ github.actor_id }}!!!"

  dime la fecha:
    steps:
      - run: date