name: Primer action
run-name: Created by ${{ github.actor }}

on: [push]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: echo "Hola github de ${{ github.actor }}!!!"

  hello_world_2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: echo "${{ github.actor }} - ${{ github.actor_id }}!!!"

  dime_la_fecha:
    runs-on: ubuntu-latest
    steps:
      - name: diciendo la fecha
        run: date
  create_a_file:
    runs-on: ubuntu-latest
    steps:
      - name: creando un archivo
        run: touch index.html
      - name: listando elementos
        run: ls -l
