name: Segundo action
run-name: Usando mi codigo del repo

on:
  push:
    banches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: install npm modules
        run: npm install
        run: npm run eslint